
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type BufferZhuanPanList struct {
    Id int32
    Rate int32
}

const TypeId_BufferZhuanPanList = 1726649159

func (*BufferZhuanPanList) GetTypeId() int32 {
    return 1726649159
}

func NewBufferZhuanPanList(_buf map[string]interface{}) (_v *BufferZhuanPanList, err error) {
    _v = &BufferZhuanPanList{}
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["id"].(float64); !_ok_ { err = errors.New("id error"); return }; _v.Id = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["rate"].(float64); !_ok_ { err = errors.New("rate error"); return }; _v.Rate = int32(_tempNum_) }
    return
}

