
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type ChangeGunBean struct {
    CoinRange *TwoIntBean
    GunRange *TwoIntBean
}

const TypeId_ChangeGunBean = 196781856

func (*ChangeGunBean) GetTypeId() int32 {
    return 196781856
}

func NewChangeGunBean(_buf map[string]interface{}) (_v *ChangeGunBean, err error) {
    _v = &ChangeGunBean{}
    { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _buf["CoinRange"].(map[string]interface{}); !_ok_ { err = errors.New("CoinRange error"); return }; if _v.CoinRange, err = NewTwoIntBean(_x_); err != nil { return } }
    { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _buf["GunRange"].(map[string]interface{}); !_ok_ { err = errors.New("GunRange error"); return }; if _v.GunRange, err = NewTwoIntBean(_x_); err != nil { return } }
    return
}

