
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type ComboReward struct {
    Id int32
    Count int32
    CoinBuffer float32
    MaxCombo int32
}

const TypeId_ComboReward = 1251029565

func (*ComboReward) GetTypeId() int32 {
    return 1251029565
}

func NewComboReward(_buf map[string]interface{}) (_v *ComboReward, err error) {
    _v = &ComboReward{}
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["id"].(float64); !_ok_ { err = errors.New("id error"); return }; _v.Id = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["count"].(float64); !_ok_ { err = errors.New("count error"); return }; _v.Count = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["coinBuffer"].(float64); !_ok_ { err = errors.New("coinBuffer error"); return }; _v.CoinBuffer = float32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["maxCombo"].(float64); !_ok_ { err = errors.New("maxCombo error"); return }; _v.MaxCombo = int32(_tempNum_) }
    return
}

