
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 小组鱼
     */
    FishType_XiaoZuYu = 1;
    /**
     * 普通鱼
     */
    FishType_PuTongYu = 2;
    /**
     * 特殊鱼
     */
    FishType_TeShuYu = 3;
)

