
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 无
     */
    FishBuffer_None = 0;
    /**
     * 冰冻
     */
    FishBuffer_BingDong = 30001;
    /**
     * 奖励珍珠
     */
    FishBuffer_RewardZhenZhu = 30002;
    /**
     * 转盘
     */
    FishBuffer_ZhuanPan = 30003;
    /**
     * 提莫的蘑菇庄园
     */
    FishBuffer_MoGu = 30004;
    /**
     * 富贵金蟾
     */
    FishBuffer_JinChan = 30005;
    /**
     * 雅典娜
     */
    FishBuffer_Athena = 30006;
    /**
     * 波塞冬
     */
    FishBuffer_Poseidon = 30007;
    /**
     * 哈迪斯
     */
    FishBuffer_Hardess = 30008;
    /**
     * 美人鱼宝箱
     */
    FishBuffer_MeiRenYuBox = 30009;
    /**
     * 奖励两个珍珠
     */
    FishBuffer_TwiceRewardZhenZhu = 30010;
    /**
     * 奖励两次转盘
     */
    FishBuffer_TwiceZhuanPan = 30011;
    /**
     * 奖励两次蘑菇庄园
     */
    FishBuffer_TwiceMoGu = 30012;
)

