
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 无
     */
    FishEnums_None = 0;
    /**
     * 小黄鱼
     */
    FishEnums_XiaoHuangYu = 501;
    /**
     * 孔雀鱼
     */
    FishEnums_KongQueYu = 502;
    /**
     * 宝石鱼
     */
    FishEnums_BaoShiYu = 503;
    /**
     * 鹦鹉鱼
     */
    FishEnums_YingWuYu = 504;
    /**
     * 花瓣鱼
     */
    FishEnums_HuaBanYu = 505;
    /**
     * 飞鱼
     */
    FishEnums_FeiYu = 506;
    /**
     * 狮子鱼
     */
    FishEnums_ShiZiYu = 507;
    /**
     * 海马
     */
    FishEnums_HaiMa = 508;
    /**
     * 剑鱼
     */
    FishEnums_JianYu = 509;
    /**
     * 小龙虾
     */
    FishEnums_XiaoLongXia = 510;
    /**
     * 盔甲鱼
     */
    FishEnums_KuiJiaYu = 511;
    /**
     * 海龟
     */
    FishEnums_HaiGui = 512;
    /**
     * 章鱼
     */
    FishEnums_ZhangYu = 513;
    /**
     * 电鳗
     */
    FishEnums_DianMan = 514;
    /**
     * 蝙蝠鱼
     */
    FishEnums_BianFUYu = 515;
    /**
     * 蓝鲨
     */
    FishEnums_LanSha = 516;
    /**
     * 金鲨
     */
    FishEnums_JinSha = 517;
    /**
     * 冰冻水母
     */
    FishEnums_BingDongShuiMu = 518;
    /**
     * 珍珠鲛人
     */
    FishEnums_ZhenZhuJiaoRen = 519;
    /**
     * 装甲章鱼
     */
    FishEnums_ZhuangJiaZhangYu = 520;
    /**
     * 鲨鱼船长
     */
    FishEnums_ShaYuChuanZhang = 521;
    /**
     * 富贵金蟾
     */
    FishEnums_FuGuiJinChan = 522;
    /**
     * 美人鱼王
     */
    FishEnums_MeiRenYuWang = 523;
    /**
     * 烈焰章鱼
     */
    FishEnums_LieYanZhangYu = 524;
    /**
     * 冰霜龙王
     */
    FishEnums_BingShuangLongWang = 525;
)

