
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type GenFishBean struct {
    FishId int32
    Num int32
    Type int32
}

const TypeId_GenFishBean = 1172692344

func (*GenFishBean) GetTypeId() int32 {
    return 1172692344
}

func NewGenFishBean(_buf map[string]interface{}) (_v *GenFishBean, err error) {
    _v = &GenFishBean{}
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["FishId"].(float64); !_ok_ { err = errors.New("FishId error"); return }; _v.FishId = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["Num"].(float64); !_ok_ { err = errors.New("Num error"); return }; _v.Num = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["Type"].(float64); !_ok_ { err = errors.New("Type error"); return }; _v.Type = int32(_tempNum_) }
    return
}

