
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type GenSpecialFinsh struct {
    Time int32
    Item []int32
}

const TypeId_GenSpecialFinsh = 1101939127

func (*GenSpecialFinsh) GetTypeId() int32 {
    return 1101939127
}

func NewGenSpecialFinsh(_buf map[string]interface{}) (_v *GenSpecialFinsh, err error) {
    _v = &GenSpecialFinsh{}
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["time"].(float64); !_ok_ { err = errors.New("time error"); return }; _v.Time = int32(_tempNum_) }
     {
                    var _arr_ []interface{}
                    var _ok_ bool
                    if _arr_, _ok_ = _buf["item"].([]interface{}); !_ok_ { err = errors.New("item error"); return }
    
                    _v.Item = make([]int32, 0, len(_arr_))
                    
                    for _, _e_ := range _arr_ {
                        var _list_v_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e_.(float64); !_ok_ { err = errors.New("_list_v_ error"); return }; _list_v_ = int32(_x_) }
                        _v.Item = append(_v.Item, _list_v_)
                    }
                }

    return
}

