
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type GoddessBlessRewardBean struct {
    Prob float32
    Reward *TwoIntBean
}

const TypeId_GoddessBlessRewardBean = 1988615197

func (*GoddessBlessRewardBean) GetTypeId() int32 {
    return 1988615197
}

func NewGoddessBlessRewardBean(_buf map[string]interface{}) (_v *GoddessBlessRewardBean, err error) {
    _v = &GoddessBlessRewardBean{}
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["Prob"].(float64); !_ok_ { err = errors.New("Prob error"); return }; _v.Prob = float32(_tempNum_) }
    { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _buf["Reward"].(map[string]interface{}); !_ok_ { err = errors.New("Reward error"); return }; if _v.Reward, err = NewTwoIntBean(_x_); err != nil { return } }
    return
}

