
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type Hardess struct {
    FishId int32
}

const TypeId_Hardess = -1933822822

func (*Hardess) GetTypeId() int32 {
    return -1933822822
}

func NewHardess(_buf map[string]interface{}) (_v *Hardess, err error) {
    _v = &Hardess{}
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["fishId"].(float64); !_ok_ { err = errors.New("fishId error"); return }; _v.FishId = int32(_tempNum_) }
    return
}

