
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 不是不死鱼
     */
    ImmortalFish_None = 0;
    /**
     * 是不死鱼
     */
    ImmortalFish_immortal = 1;
)

