
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type LaBa struct {
    Id int32
    Roller []int32
    FishRate []*LaBaFishRate
}

const TypeId_LaBa = 2359476

func (*LaBa) GetTypeId() int32 {
    return 2359476
}

func NewLaBa(_buf map[string]interface{}) (_v *LaBa, err error) {
    _v = &LaBa{}
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["id"].(float64); !_ok_ { err = errors.New("id error"); return }; _v.Id = int32(_tempNum_) }
     {
                    var _arr_ []interface{}
                    var _ok_ bool
                    if _arr_, _ok_ = _buf["roller"].([]interface{}); !_ok_ { err = errors.New("roller error"); return }
    
                    _v.Roller = make([]int32, 0, len(_arr_))
                    
                    for _, _e_ := range _arr_ {
                        var _list_v_ int32
                        { var _ok_ bool; var _x_ float64; if _x_, _ok_ = _e_.(float64); !_ok_ { err = errors.New("_list_v_ error"); return }; _list_v_ = int32(_x_) }
                        _v.Roller = append(_v.Roller, _list_v_)
                    }
                }

     {
                    var _arr_ []interface{}
                    var _ok_ bool
                    if _arr_, _ok_ = _buf["fishRate"].([]interface{}); !_ok_ { err = errors.New("fishRate error"); return }
    
                    _v.FishRate = make([]*LaBaFishRate, 0, len(_arr_))
                    
                    for _, _e_ := range _arr_ {
                        var _list_v_ *LaBaFishRate
                        { var _ok_ bool; var _x_ map[string]interface{}; if _x_, _ok_ = _e_.(map[string]interface{}); !_ok_ { err = errors.New("_list_v_ error"); return }; if _list_v_, err = NewLaBaFishRate(_x_); err != nil { return } }
                        _v.FishRate = append(_v.FishRate, _list_v_)
                    }
                }

    return
}

