
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type LaBaFishRate struct {
    FishId int32
    Rate int32
}

const TypeId_LaBaFishRate = -1067434964

func (*LaBaFishRate) GetTypeId() int32 {
    return -1067434964
}

func NewLaBaFishRate(_buf map[string]interface{}) (_v *LaBaFishRate, err error) {
    _v = &LaBaFishRate{}
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["FishId"].(float64); !_ok_ { err = errors.New("FishId error"); return }; _v.FishId = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["Rate"].(float64); !_ok_ { err = errors.New("Rate error"); return }; _v.Rate = int32(_tempNum_) }
    return
}

