
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type MoGu struct {
    Id int32
    Name string
    Rate int32
    Prob float32
}

const TypeId_MoGu = 2402896

func (*MoGu) GetTypeId() int32 {
    return 2402896
}

func NewMoGu(_buf map[string]interface{}) (_v *MoGu, err error) {
    _v = &MoGu{}
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["id"].(float64); !_ok_ { err = errors.New("id error"); return }; _v.Id = int32(_tempNum_) }
    { var _ok_ bool; if _v.Name, _ok_ = _buf["name"].(string); !_ok_ { err = errors.New("name error"); return } }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["rate"].(float64); !_ok_ { err = errors.New("rate error"); return }; _v.Rate = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["prob"].(float64); !_ok_ { err = errors.New("prob error"); return }; _v.Prob = float32(_tempNum_) }
    return
}

