
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type Poseidon struct {
    Id int32
}

const TypeId_Poseidon = 808422507

func (*Poseidon) GetTypeId() int32 {
    return 808422507
}

func NewPoseidon(_buf map[string]interface{}) (_v *Poseidon, err error) {
    _v = &Poseidon{}
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["id"].(float64); !_ok_ { err = errors.New("id error"); return }; _v.Id = int32(_tempNum_) }
    return
}

