
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 机器人行为：锁定
     */
    RobotActionEnums_SuoDing = 1;
    /**
     * 自动开炮
     */
    RobotActionEnums_ZiDongGun = 2;
    /**
     * 手动开炮
     */
    RobotActionEnums_ShouDongGun = 3;
)

