
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 圣域
     */
    RoomType_ShengYu = 0;
    /**
     * 海底
     */
    RoomType_HaiDi = 1;
    /**
     * 冥界
     */
    RoomType_MingJie = 2;
)

