
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

const (
    /**
     * 屏幕左边
     */
    ScreenDirection_ScreenLeft = 1;
    /**
     * 屏幕右边
     */
    ScreenDirection_ScreenRight = 2;
)

