
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type SpecialFormat4Bean struct {
    YLine int32
    FishId int32
    Num int32
}

const TypeId_SpecialFormat4Bean = -1099407852

func (*SpecialFormat4Bean) GetTypeId() int32 {
    return -1099407852
}

func NewSpecialFormat4Bean(_buf map[string]interface{}) (_v *SpecialFormat4Bean, err error) {
    _v = &SpecialFormat4Bean{}
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["YLine"].(float64); !_ok_ { err = errors.New("YLine error"); return }; _v.YLine = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["FishId"].(float64); !_ok_ { err = errors.New("FishId error"); return }; _v.FishId = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["Num"].(float64); !_ok_ { err = errors.New("Num error"); return }; _v.Num = int32(_tempNum_) }
    return
}

