
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type TableFishInfo struct {
    _dataMap map[int32]*FishInfo
    _dataList []*FishInfo
}

func NewTableFishInfo(_buf []map[string]interface{}) (*TableFishInfo, error) {
    _dataList := make([]*FishInfo, 0, len(_buf))
    dataMap := make(map[int32]*FishInfo)

    for _, _ele_ := range _buf {
        if _v, err2 := NewFishInfo(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.FishId] = _v
        }
    }
    return &TableFishInfo{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TableFishInfo) GetDataMap() map[int32]*FishInfo {
    return table._dataMap
}

func (table *TableFishInfo) GetDataList() []*FishInfo {
    return table._dataList
}

func (table *TableFishInfo) Get(key int32) *FishInfo {
    return table._dataMap[key]
}


