
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type TableGenSpecialFish struct {
    _dataMap map[int32]*GenSpecialFinsh
    _dataList []*GenSpecialFinsh
}

func NewTableGenSpecialFish(_buf []map[string]interface{}) (*TableGenSpecialFish, error) {
    _dataList := make([]*GenSpecialFinsh, 0, len(_buf))
    dataMap := make(map[int32]*GenSpecialFinsh)

    for _, _ele_ := range _buf {
        if _v, err2 := NewGenSpecialFinsh(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Time] = _v
        }
    }
    return &TableGenSpecialFish{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TableGenSpecialFish) GetDataMap() map[int32]*GenSpecialFinsh {
    return table._dataMap
}

func (table *TableGenSpecialFish) GetDataList() []*GenSpecialFinsh {
    return table._dataList
}

func (table *TableGenSpecialFish) Get(key int32) *GenSpecialFinsh {
    return table._dataMap[key]
}


