
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type TableRobotConfig struct {
    _dataMap map[int32]*RobotConfig
    _dataList []*RobotConfig
}

func NewTableRobotConfig(_buf []map[string]interface{}) (*TableRobotConfig, error) {
    _dataList := make([]*RobotConfig, 0, len(_buf))
    dataMap := make(map[int32]*RobotConfig)

    for _, _ele_ := range _buf {
        if _v, err2 := NewRobotConfig(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.RoomType] = _v
        }
    }
    return &TableRobotConfig{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TableRobotConfig) GetDataMap() map[int32]*RobotConfig {
    return table._dataMap
}

func (table *TableRobotConfig) GetDataList() []*RobotConfig {
    return table._dataList
}

func (table *TableRobotConfig) Get(key int32) *RobotConfig {
    return table._dataMap[key]
}


