
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

type JsonLoader func(string) ([]map[string]interface{}, error)

type Tables struct {
    TableFishInfo *TableFishInfo
    TableGenFish *TableGenFish
    TableGenSpecialFish *TableGenSpecialFish
    TableSpecialFormat1 *TableSpecialFormat1
    TableSpecialFormat2 *TableSpecialFormat2
    TableSpecialFormat3 *TableSpecialFormat3
    TableSpecialFormat4 *TableSpecialFormat4
    TableRoomConfig *TableRoomConfig
    TableRobotConfig *TableRobotConfig
    TableRobotAction *TableRobotAction
    XiaoYouXiLaBa *XiaoYouXiLaBa
    XiaoYouXiBufferZhuanPanConfig *XiaoYouXiBufferZhuanPanConfig
    XiaoYouXiBufferZhuanPanList *XiaoYouXiBufferZhuanPanList
    XiaoYouXiMoGu *XiaoYouXiMoGu
    XiaoYouXiJinChan *XiaoYouXiJinChan
    XiaoYouXiAthena *XiaoYouXiAthena
    XiaoYouXiPoseidon *XiaoYouXiPoseidon
    XiaoYouXiHardess *XiaoYouXiHardess
    XiaoYouXiActivityZhuanPan *XiaoYouXiActivityZhuanPan
    XiaoYouXiGoddessBless *XiaoYouXiGoddessBless
    XiaoYouXiComboReward *XiaoYouXiComboReward
}

func NewTables(loader JsonLoader) (*Tables, error) {
    var err error
    var buf []map[string]interface{}

    tables := &Tables{}
    if buf, err = loader("tablefishinfo") ; err != nil {
        return nil, err
    }
    if tables.TableFishInfo, err = NewTableFishInfo(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tablegenfish") ; err != nil {
        return nil, err
    }
    if tables.TableGenFish, err = NewTableGenFish(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tablegenspecialfish") ; err != nil {
        return nil, err
    }
    if tables.TableGenSpecialFish, err = NewTableGenSpecialFish(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tablespecialformat1") ; err != nil {
        return nil, err
    }
    if tables.TableSpecialFormat1, err = NewTableSpecialFormat1(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tablespecialformat2") ; err != nil {
        return nil, err
    }
    if tables.TableSpecialFormat2, err = NewTableSpecialFormat2(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tablespecialformat3") ; err != nil {
        return nil, err
    }
    if tables.TableSpecialFormat3, err = NewTableSpecialFormat3(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tablespecialformat4") ; err != nil {
        return nil, err
    }
    if tables.TableSpecialFormat4, err = NewTableSpecialFormat4(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tableroomconfig") ; err != nil {
        return nil, err
    }
    if tables.TableRoomConfig, err = NewTableRoomConfig(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tablerobotconfig") ; err != nil {
        return nil, err
    }
    if tables.TableRobotConfig, err = NewTableRobotConfig(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tablerobotaction") ; err != nil {
        return nil, err
    }
    if tables.TableRobotAction, err = NewTableRobotAction(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("xiaoyouxilaba") ; err != nil {
        return nil, err
    }
    if tables.XiaoYouXiLaBa, err = NewXiaoYouXiLaBa(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("xiaoyouxibufferzhuanpanconfig") ; err != nil {
        return nil, err
    }
    if tables.XiaoYouXiBufferZhuanPanConfig, err = NewXiaoYouXiBufferZhuanPanConfig(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("xiaoyouxibufferzhuanpanlist") ; err != nil {
        return nil, err
    }
    if tables.XiaoYouXiBufferZhuanPanList, err = NewXiaoYouXiBufferZhuanPanList(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("xiaoyouximogu") ; err != nil {
        return nil, err
    }
    if tables.XiaoYouXiMoGu, err = NewXiaoYouXiMoGu(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("xiaoyouxijinchan") ; err != nil {
        return nil, err
    }
    if tables.XiaoYouXiJinChan, err = NewXiaoYouXiJinChan(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("xiaoyouxiathena") ; err != nil {
        return nil, err
    }
    if tables.XiaoYouXiAthena, err = NewXiaoYouXiAthena(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("xiaoyouxiposeidon") ; err != nil {
        return nil, err
    }
    if tables.XiaoYouXiPoseidon, err = NewXiaoYouXiPoseidon(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("xiaoyouxihardess") ; err != nil {
        return nil, err
    }
    if tables.XiaoYouXiHardess, err = NewXiaoYouXiHardess(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("xiaoyouxiactivityzhuanpan") ; err != nil {
        return nil, err
    }
    if tables.XiaoYouXiActivityZhuanPan, err = NewXiaoYouXiActivityZhuanPan(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("xiaoyouxigoddessbless") ; err != nil {
        return nil, err
    }
    if tables.XiaoYouXiGoddessBless, err = NewXiaoYouXiGoddessBless(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("xiaoyouxicomboreward") ; err != nil {
        return nil, err
    }
    if tables.XiaoYouXiComboReward, err = NewXiaoYouXiComboReward(buf) ; err != nil {
        return nil, err
    }
    return tables, nil
}


