
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type TableGenFish struct {
    _dataMap map[int32]*GenFish
    _dataList []*GenFish
}

func NewTableGenFish(_buf []map[string]interface{}) (*TableGenFish, error) {
    _dataList := make([]*GenFish, 0, len(_buf))
    dataMap := make(map[int32]*GenFish)

    for _, _ele_ := range _buf {
        if _v, err2 := NewGenFish(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.RoundId] = _v
        }
    }
    return &TableGenFish{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TableGenFish) GetDataMap() map[int32]*GenFish {
    return table._dataMap
}

func (table *TableGenFish) GetDataList() []*GenFish {
    return table._dataList
}

func (table *TableGenFish) Get(key int32) *GenFish {
    return table._dataMap[key]
}


