
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type TableSpecialFormat2 struct {
    _dataMap map[int32]*SpecialFormat2
    _dataList []*SpecialFormat2
}

func NewTableSpecialFormat2(_buf []map[string]interface{}) (*TableSpecialFormat2, error) {
    _dataList := make([]*SpecialFormat2, 0, len(_buf))
    dataMap := make(map[int32]*SpecialFormat2)

    for _, _ele_ := range _buf {
        if _v, err2 := NewSpecialFormat2(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Lot] = _v
        }
    }
    return &TableSpecialFormat2{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TableSpecialFormat2) GetDataMap() map[int32]*SpecialFormat2 {
    return table._dataMap
}

func (table *TableSpecialFormat2) GetDataList() []*SpecialFormat2 {
    return table._dataList
}

func (table *TableSpecialFormat2) Get(key int32) *SpecialFormat2 {
    return table._dataMap[key]
}


