
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type TableRoomConfig struct {
    _dataMap map[int32]*RoomConfig
    _dataList []*RoomConfig
}

func NewTableRoomConfig(_buf []map[string]interface{}) (*TableRoomConfig, error) {
    _dataList := make([]*RoomConfig, 0, len(_buf))
    dataMap := make(map[int32]*RoomConfig)

    for _, _ele_ := range _buf {
        if _v, err2 := NewRoomConfig(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.RoomType] = _v
        }
    }
    return &TableRoomConfig{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TableRoomConfig) GetDataMap() map[int32]*RoomConfig {
    return table._dataMap
}

func (table *TableRoomConfig) GetDataList() []*RoomConfig {
    return table._dataList
}

func (table *TableRoomConfig) Get(key int32) *RoomConfig {
    return table._dataMap[key]
}


