
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type TwoFloatBean struct {
    One float32
    Two float32
}

const TypeId_TwoFloatBean = -1576885408

func (*TwoFloatBean) GetTypeId() int32 {
    return -1576885408
}

func NewTwoFloatBean(_buf map[string]interface{}) (_v *TwoFloatBean, err error) {
    _v = &TwoFloatBean{}
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["One"].(float64); !_ok_ { err = errors.New("One error"); return }; _v.One = float32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["Two"].(float64); !_ok_ { err = errors.New("Two error"); return }; _v.Two = float32(_tempNum_) }
    return
}

