
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type TwoIntBean struct {
    One int32
    Two int32
}

const TypeId_TwoIntBean = -160869261

func (*TwoIntBean) GetTypeId() int32 {
    return -160869261
}

func NewTwoIntBean(_buf map[string]interface{}) (_v *TwoIntBean, err error) {
    _v = &TwoIntBean{}
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["One"].(float64); !_ok_ { err = errors.New("One error"); return }; _v.One = int32(_tempNum_) }
    { var _ok_ bool; var _tempNum_ float64; if _tempNum_, _ok_ = _buf["Two"].(float64); !_ok_ { err = errors.New("Two error"); return }; _v.Two = int32(_tempNum_) }
    return
}

