
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type XiaoYouXiBufferZhuanPanList struct {
    _dataMap map[int32]*BufferZhuanPanList
    _dataList []*BufferZhuanPanList
}

func NewXiaoYouXiBufferZhuanPanList(_buf []map[string]interface{}) (*XiaoYouXiBufferZhuanPanList, error) {
    _dataList := make([]*BufferZhuanPanList, 0, len(_buf))
    dataMap := make(map[int32]*BufferZhuanPanList)

    for _, _ele_ := range _buf {
        if _v, err2 := NewBufferZhuanPanList(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &XiaoYouXiBufferZhuanPanList{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *XiaoYouXiBufferZhuanPanList) GetDataMap() map[int32]*BufferZhuanPanList {
    return table._dataMap
}

func (table *XiaoYouXiBufferZhuanPanList) GetDataList() []*BufferZhuanPanList {
    return table._dataList
}

func (table *XiaoYouXiBufferZhuanPanList) Get(key int32) *BufferZhuanPanList {
    return table._dataMap[key]
}


