
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type XiaoYouXiLaBa struct {
    _dataMap map[int32]*LaBa
    _dataList []*LaBa
}

func NewXiaoYouXiLaBa(_buf []map[string]interface{}) (*XiaoYouXiLaBa, error) {
    _dataList := make([]*LaBa, 0, len(_buf))
    dataMap := make(map[int32]*LaBa)

    for _, _ele_ := range _buf {
        if _v, err2 := NewLaBa(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &XiaoYouXiLaBa{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *XiaoYouXiLaBa) GetDataMap() map[int32]*LaBa {
    return table._dataMap
}

func (table *XiaoYouXiLaBa) GetDataList() []*LaBa {
    return table._dataList
}

func (table *XiaoYouXiLaBa) Get(key int32) *LaBa {
    return table._dataMap[key]
}


