
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type XiaoYouXiGoddessBless struct {
    _dataMap map[int32]*GoddessBless
    _dataList []*GoddessBless
}

func NewXiaoYouXiGoddessBless(_buf []map[string]interface{}) (*XiaoYouXiGoddessBless, error) {
    _dataList := make([]*GoddessBless, 0, len(_buf))
    dataMap := make(map[int32]*GoddessBless)

    for _, _ele_ := range _buf {
        if _v, err2 := NewGoddessBless(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.RoomType] = _v
        }
    }
    return &XiaoYouXiGoddessBless{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *XiaoYouXiGoddessBless) GetDataMap() map[int32]*GoddessBless {
    return table._dataMap
}

func (table *XiaoYouXiGoddessBless) GetDataList() []*GoddessBless {
    return table._dataList
}

func (table *XiaoYouXiGoddessBless) Get(key int32) *GoddessBless {
    return table._dataMap[key]
}


