
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type XiaoYouXiHardess struct {
    _dataMap map[int32]*Hardess
    _dataList []*Hardess
}

func NewXiaoYouXiHardess(_buf []map[string]interface{}) (*XiaoYouXiHardess, error) {
    _dataList := make([]*Hardess, 0, len(_buf))
    dataMap := make(map[int32]*Hardess)

    for _, _ele_ := range _buf {
        if _v, err2 := NewHardess(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.FishId] = _v
        }
    }
    return &XiaoYouXiHardess{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *XiaoYouXiHardess) GetDataMap() map[int32]*Hardess {
    return table._dataMap
}

func (table *XiaoYouXiHardess) GetDataList() []*Hardess {
    return table._dataList
}

func (table *XiaoYouXiHardess) Get(key int32) *Hardess {
    return table._dataMap[key]
}


