
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type XiaoYouXiJinChan struct {
    _dataMap map[int32]*JinChan
    _dataList []*JinChan
}

func NewXiaoYouXiJinChan(_buf []map[string]interface{}) (*XiaoYouXiJinChan, error) {
    _dataList := make([]*JinChan, 0, len(_buf))
    dataMap := make(map[int32]*JinChan)

    for _, _ele_ := range _buf {
        if _v, err2 := NewJinChan(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &XiaoYouXiJinChan{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *XiaoYouXiJinChan) GetDataMap() map[int32]*JinChan {
    return table._dataMap
}

func (table *XiaoYouXiJinChan) GetDataList() []*JinChan {
    return table._dataList
}

func (table *XiaoYouXiJinChan) Get(key int32) *JinChan {
    return table._dataMap[key]
}


