
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type XiaoYouXiMoGu struct {
    _dataMap map[int32]*MoGu
    _dataList []*MoGu
}

func NewXiaoYouXiMoGu(_buf []map[string]interface{}) (*XiaoYouXiMoGu, error) {
    _dataList := make([]*MoGu, 0, len(_buf))
    dataMap := make(map[int32]*MoGu)

    for _, _ele_ := range _buf {
        if _v, err2 := NewMoGu(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &XiaoYouXiMoGu{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *XiaoYouXiMoGu) GetDataMap() map[int32]*MoGu {
    return table._dataMap
}

func (table *XiaoYouXiMoGu) GetDataList() []*MoGu {
    return table._dataList
}

func (table *XiaoYouXiMoGu) Get(key int32) *MoGu {
    return table._dataMap[key]
}


