
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type XiaoYouXiActivityZhuanPan struct {
    _dataMap map[int32]*ActivityZhuanPan
    _dataList []*ActivityZhuanPan
}

func NewXiaoYouXiActivityZhuanPan(_buf []map[string]interface{}) (*XiaoYouXiActivityZhuanPan, error) {
    _dataList := make([]*ActivityZhuanPan, 0, len(_buf))
    dataMap := make(map[int32]*ActivityZhuanPan)

    for _, _ele_ := range _buf {
        if _v, err2 := NewActivityZhuanPan(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &XiaoYouXiActivityZhuanPan{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *XiaoYouXiActivityZhuanPan) GetDataMap() map[int32]*ActivityZhuanPan {
    return table._dataMap
}

func (table *XiaoYouXiActivityZhuanPan) GetDataList() []*ActivityZhuanPan {
    return table._dataList
}

func (table *XiaoYouXiActivityZhuanPan) Get(key int32) *ActivityZhuanPan {
    return table._dataMap[key]
}


