
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type XiaoYouXiBufferZhuanPanConfig struct {
    _dataMap map[int32]*BufferZhuanPanConfig
    _dataList []*BufferZhuanPanConfig
}

func NewXiaoYouXiBufferZhuanPanConfig(_buf []map[string]interface{}) (*XiaoYouXiBufferZhuanPanConfig, error) {
    _dataList := make([]*BufferZhuanPanConfig, 0, len(_buf))
    dataMap := make(map[int32]*BufferZhuanPanConfig)

    for _, _ele_ := range _buf {
        if _v, err2 := NewBufferZhuanPanConfig(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.CellNum] = _v
        }
    }
    return &XiaoYouXiBufferZhuanPanConfig{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *XiaoYouXiBufferZhuanPanConfig) GetDataMap() map[int32]*BufferZhuanPanConfig {
    return table._dataMap
}

func (table *XiaoYouXiBufferZhuanPanConfig) GetDataList() []*BufferZhuanPanConfig {
    return table._dataList
}

func (table *XiaoYouXiBufferZhuanPanConfig) Get(key int32) *BufferZhuanPanConfig {
    return table._dataMap[key]
}


