
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type XiaoYouXiAthena struct {
    _dataMap map[int32]*Athena
    _dataList []*Athena
}

func NewXiaoYouXiAthena(_buf []map[string]interface{}) (*XiaoYouXiAthena, error) {
    _dataList := make([]*Athena, 0, len(_buf))
    dataMap := make(map[int32]*Athena)

    for _, _ele_ := range _buf {
        if _v, err2 := NewAthena(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &XiaoYouXiAthena{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *XiaoYouXiAthena) GetDataMap() map[int32]*Athena {
    return table._dataMap
}

func (table *XiaoYouXiAthena) GetDataList() []*Athena {
    return table._dataList
}

func (table *XiaoYouXiAthena) Get(key int32) *Athena {
    return table._dataMap[key]
}


