
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type XiaoYouXiComboReward struct {
    _dataMap map[int32]*ComboReward
    _dataList []*ComboReward
}

func NewXiaoYouXiComboReward(_buf []map[string]interface{}) (*XiaoYouXiComboReward, error) {
    _dataList := make([]*ComboReward, 0, len(_buf))
    dataMap := make(map[int32]*ComboReward)

    for _, _ele_ := range _buf {
        if _v, err2 := NewComboReward(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &XiaoYouXiComboReward{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *XiaoYouXiComboReward) GetDataMap() map[int32]*ComboReward {
    return table._dataMap
}

func (table *XiaoYouXiComboReward) GetDataList() []*ComboReward {
    return table._dataList
}

func (table *XiaoYouXiComboReward) Get(key int32) *ComboReward {
    return table._dataMap[key]
}


