// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: rpc.proto

package rpc_proto

import (
	common_proto "bygame/common/proto/common_proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RpcCmdId int32

const (
	RpcCmdId__cmdId      RpcCmdId = 0
	RpcCmdId_C2Game      RpcCmdId = 1 // 网关转发客户端消息到游戏服
	RpcCmdId_Game2C      RpcCmdId = 2 // 游戏服消息转发到客户端
	RpcCmdId_Login       RpcCmdId = 3 // 玩家登录网关，之后通知游戏服
	RpcCmdId_Offline     RpcCmdId = 4 // 玩家断线，通知游戏服
	RpcCmdId_KickoutGate RpcCmdId = 5 // 踢下线
)

// Enum value maps for RpcCmdId.
var (
	RpcCmdId_name = map[int32]string{
		0: "_cmdId",
		1: "C2Game",
		2: "Game2C",
		3: "Login",
		4: "Offline",
		5: "KickoutGate",
	}
	RpcCmdId_value = map[string]int32{
		"_cmdId":      0,
		"C2Game":      1,
		"Game2C":      2,
		"Login":       3,
		"Offline":     4,
		"KickoutGate": 5,
	}
)

func (x RpcCmdId) Enum() *RpcCmdId {
	p := new(RpcCmdId)
	*p = x
	return p
}

func (x RpcCmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RpcCmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_enumTypes[0].Descriptor()
}

func (RpcCmdId) Type() protoreflect.EnumType {
	return &file_rpc_proto_enumTypes[0]
}

func (x RpcCmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RpcCmdId.Descriptor instead.
func (RpcCmdId) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{0}
}

type BaseRpc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RcpId   int32  `protobuf:"varint,1,opt,name=rcpId,proto3" json:"rcpId,omitempty"`    // rpcId
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // 消息体
	From    string `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`       // 来自哪个服
	ReqId   string `protobuf:"bytes,4,opt,name=reqId,proto3" json:"reqId,omitempty"`     // 请求id
	Code    int32  `protobuf:"varint,5,opt,name=code,proto3" json:"code,omitempty"`      // 错误id
	Msg     string `protobuf:"bytes,6,opt,name=msg,proto3" json:"msg,omitempty"`         // 错误信息
	Req     bool   `protobuf:"varint,7,opt,name=req,proto3" json:"req,omitempty"`        // 是否是请求
}

func (x *BaseRpc) Reset() {
	*x = BaseRpc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseRpc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseRpc) ProtoMessage() {}

func (x *BaseRpc) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseRpc.ProtoReflect.Descriptor instead.
func (*BaseRpc) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *BaseRpc) GetRcpId() int32 {
	if x != nil {
		return x.RcpId
	}
	return 0
}

func (x *BaseRpc) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BaseRpc) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *BaseRpc) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

func (x *BaseRpc) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseRpc) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *BaseRpc) GetReq() bool {
	if x != nil {
		return x.Req
	}
	return false
}

// 客户端请求通过网关转发到游戏服
type ReqC2Game struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientCmd *common_proto.BaseCmd `protobuf:"bytes,1,opt,name=clientCmd,proto3" json:"clientCmd,omitempty"`
	Mid       string                `protobuf:"bytes,2,opt,name=mid,proto3" json:"mid,omitempty"`
}

func (x *ReqC2Game) Reset() {
	*x = ReqC2Game{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqC2Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqC2Game) ProtoMessage() {}

func (x *ReqC2Game) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqC2Game.ProtoReflect.Descriptor instead.
func (*ReqC2Game) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *ReqC2Game) GetClientCmd() *common_proto.BaseCmd {
	if x != nil {
		return x.ClientCmd
	}
	return nil
}

func (x *ReqC2Game) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

type RetC2Game struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RetC2Game) Reset() {
	*x = RetC2Game{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetC2Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetC2Game) ProtoMessage() {}

func (x *RetC2Game) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetC2Game.ProtoReflect.Descriptor instead.
func (*RetC2Game) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{2}
}

type ReqGame2C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientCmd *common_proto.BaseCmd `protobuf:"bytes,1,opt,name=clientCmd,proto3" json:"clientCmd,omitempty"`
	Mid       string                `protobuf:"bytes,2,opt,name=mid,proto3" json:"mid,omitempty"`
}

func (x *ReqGame2C) Reset() {
	*x = ReqGame2C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGame2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGame2C) ProtoMessage() {}

func (x *ReqGame2C) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGame2C.ProtoReflect.Descriptor instead.
func (*ReqGame2C) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *ReqGame2C) GetClientCmd() *common_proto.BaseCmd {
	if x != nil {
		return x.ClientCmd
	}
	return nil
}

func (x *ReqGame2C) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

type RetGame2C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RetGame2C) Reset() {
	*x = RetGame2C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetGame2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetGame2C) ProtoMessage() {}

func (x *RetGame2C) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetGame2C.ProtoReflect.Descriptor instead.
func (*RetGame2C) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{4}
}

// 玩家登录
type ReqLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mid          string `protobuf:"bytes,1,opt,name=mid,proto3" json:"mid,omitempty"`                   // 玩家mid
	GateServerId string `protobuf:"bytes,2,opt,name=gateServerId,proto3" json:"gateServerId,omitempty"` // 网关服
}

func (x *ReqLogin) Reset() {
	*x = ReqLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLogin) ProtoMessage() {}

func (x *ReqLogin) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLogin.ProtoReflect.Descriptor instead.
func (*ReqLogin) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *ReqLogin) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

func (x *ReqLogin) GetGateServerId() string {
	if x != nil {
		return x.GateServerId
	}
	return ""
}

type RetLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RetLogin) Reset() {
	*x = RetLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetLogin) ProtoMessage() {}

func (x *RetLogin) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetLogin.ProtoReflect.Descriptor instead.
func (*RetLogin) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{6}
}

// 玩家断开连接
type ReqOffline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mid string `protobuf:"bytes,1,opt,name=mid,proto3" json:"mid,omitempty"` // 玩家id
}

func (x *ReqOffline) Reset() {
	*x = ReqOffline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqOffline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqOffline) ProtoMessage() {}

func (x *ReqOffline) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqOffline.ProtoReflect.Descriptor instead.
func (*ReqOffline) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *ReqOffline) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

type RetOffline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RetOffline) Reset() {
	*x = RetOffline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetOffline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetOffline) ProtoMessage() {}

func (x *RetOffline) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetOffline.ProtoReflect.Descriptor instead.
func (*RetOffline) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{8}
}

type ReqKickoutGate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mid string `protobuf:"bytes,1,opt,name=mid,proto3" json:"mid,omitempty"` // 玩家id
}

func (x *ReqKickoutGate) Reset() {
	*x = ReqKickoutGate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqKickoutGate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqKickoutGate) ProtoMessage() {}

func (x *ReqKickoutGate) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqKickoutGate.ProtoReflect.Descriptor instead.
func (*ReqKickoutGate) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *ReqKickoutGate) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

type RetKickoutGate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RetKickoutGate) Reset() {
	*x = RetKickoutGate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetKickoutGate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetKickoutGate) ProtoMessage() {}

func (x *RetKickoutGate) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetKickoutGate.ProtoReflect.Descriptor instead.
func (*RetKickoutGate) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{10}
}

var File_rpc_proto protoreflect.FileDescriptor

var file_rpc_proto_rawDesc = []byte{
	0x0a, 0x09, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63,
	0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9b,
	0x01, 0x0a, 0x07, 0x42, 0x61, 0x73, 0x65, 0x52, 0x70, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x63,
	0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x63, 0x70, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x14,
	0x0a, 0x05, 0x72, 0x65, 0x71, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72,
	0x65, 0x71, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65,
	0x71, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x72, 0x65, 0x71, 0x22, 0x4c, 0x0a, 0x09,
	0x52, 0x65, 0x71, 0x43, 0x32, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x43, 0x6d, 0x64, 0x52, 0x09, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6d, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x69, 0x64, 0x22, 0x0b, 0x0a, 0x09, 0x52, 0x65,
	0x74, 0x43, 0x32, 0x47, 0x61, 0x6d, 0x65, 0x22, 0x4c, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x47, 0x61,
	0x6d, 0x65, 0x32, 0x43, 0x12, 0x2d, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6d,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x42, 0x61, 0x73, 0x65, 0x43, 0x6d, 0x64, 0x52, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x43, 0x6d, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x69, 0x64, 0x22, 0x0b, 0x0a, 0x09, 0x52, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65,
	0x32, 0x43, 0x22, 0x40, 0x0a, 0x08, 0x52, 0x65, 0x71, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x69, 0x64,
	0x12, 0x22, 0x0a, 0x0c, 0x67, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x67, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x22, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x69, 0x64,
	0x22, 0x0c, 0x0a, 0x0a, 0x52, 0x65, 0x74, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0x22,
	0x0a, 0x0e, 0x52, 0x65, 0x71, 0x4b, 0x69, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x47, 0x61, 0x74, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x69, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x52, 0x65, 0x74, 0x4b, 0x69, 0x63, 0x6b, 0x6f, 0x75, 0x74,
	0x47, 0x61, 0x74, 0x65, 0x2a, 0x57, 0x0a, 0x08, 0x52, 0x70, 0x63, 0x43, 0x6d, 0x64, 0x49, 0x64,
	0x12, 0x0a, 0x0a, 0x06, 0x5f, 0x63, 0x6d, 0x64, 0x49, 0x64, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x43, 0x32, 0x47, 0x61, 0x6d, 0x65, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65,
	0x32, 0x43, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x10, 0x03, 0x12,
	0x0b, 0x0a, 0x07, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b,
	0x4b, 0x69, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x47, 0x61, 0x74, 0x65, 0x10, 0x05, 0x42, 0x1f, 0x5a,
	0x1d, 0x62, 0x79, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_proto_rawDescOnce sync.Once
	file_rpc_proto_rawDescData = file_rpc_proto_rawDesc
)

func file_rpc_proto_rawDescGZIP() []byte {
	file_rpc_proto_rawDescOnce.Do(func() {
		file_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_proto_rawDescData)
	})
	return file_rpc_proto_rawDescData
}

var file_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_rpc_proto_goTypes = []interface{}{
	(RpcCmdId)(0),                // 0: rpc.RpcCmdId
	(*BaseRpc)(nil),              // 1: rpc.BaseRpc
	(*ReqC2Game)(nil),            // 2: rpc.ReqC2Game
	(*RetC2Game)(nil),            // 3: rpc.RetC2Game
	(*ReqGame2C)(nil),            // 4: rpc.ReqGame2C
	(*RetGame2C)(nil),            // 5: rpc.RetGame2C
	(*ReqLogin)(nil),             // 6: rpc.ReqLogin
	(*RetLogin)(nil),             // 7: rpc.RetLogin
	(*ReqOffline)(nil),           // 8: rpc.ReqOffline
	(*RetOffline)(nil),           // 9: rpc.RetOffline
	(*ReqKickoutGate)(nil),       // 10: rpc.ReqKickoutGate
	(*RetKickoutGate)(nil),       // 11: rpc.RetKickoutGate
	(*common_proto.BaseCmd)(nil), // 12: common.BaseCmd
}
var file_rpc_proto_depIdxs = []int32{
	12, // 0: rpc.ReqC2Game.clientCmd:type_name -> common.BaseCmd
	12, // 1: rpc.ReqGame2C.clientCmd:type_name -> common.BaseCmd
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_proto_init() }
func file_rpc_proto_init() {
	if File_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseRpc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqC2Game); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetC2Game); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGame2C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetGame2C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqOffline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetOffline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqKickoutGate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetKickoutGate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_proto_goTypes,
		DependencyIndexes: file_rpc_proto_depIdxs,
		EnumInfos:         file_rpc_proto_enumTypes,
		MessageInfos:      file_rpc_proto_msgTypes,
	}.Build()
	File_rpc_proto = out.File
	file_rpc_proto_rawDesc = nil
	file_rpc_proto_goTypes = nil
	file_rpc_proto_depIdxs = nil
}
